databricks_resources:
  genie_space_id: [genie_space_id]
  genie_workspace_host: [workspace_host]
  llm_endpoint_name: databricks-meta-llama-3-1-70b-instruct
  vector_search_endpoint_name: [endpoint]
  warehouse_id: [warehouse_id]
  unity_catalog_functions: [catalog].[database].*
input_example:
  messages:
  - content: Sample user question
    role: user
llm_config:
  llm_parameters:
    max_tokens: 1500
    temperature: 0.01

retriever_config:
  chunk_template: 'Passage: {chunk_text}

    '
  data_pipeline_tag: poc
  parameters:
    k: 5
    query_type: ann
  schema:
    chunk_text: content
    document_uri: url
    primary_key: id
  vector_search_index: [catalog].[database].[index]
