databricks_resources:

  catalog_name: pandas_poc
  database_name: quisitive
  volume_name: raw

  registered_model_name: "pandas_poc.quisitive.compound_ai_langgraph"

  genie_space_id: 01efa0fa59d61c509a31665344f6c739
  genie_workspace_host: adb-984752964297111.11.azuredatabricks.net
  llm_endpoint_name: databricks-meta-llama-3-1-70b-instruct

  embedding_model_endpoint_name: databricks-gte-large-en
  vector_search_endpoint_name: one-env-shared-endpoint-12

  warehouse_id: foo
  unity_catalog_functions: "pandas_poc.quisitive.*"
  
  evaluation_table_name: pandas_poc.quisitive.evaluation
  
  users:
  - nate.fleming@databricks.com
  - dipankar.kushari@databricks.com
  - hersh.anand@databricks.com

input_example:
  messages:
  - content: What id Databricks?
    role: user
retriever_config:
  chunk_template: 'Passage: {chunk_text}

    '
  data_pipeline_tag: poc
  parameters:
    k: 5
    query_type: ann
  schema:
    embedding_source_column: content
    document_uri: url
    primary_key: id
  vector_search_index: pandas_poc.quisitive.documents_chunked_vs_index
  source_table_name: pandas_poc.quisitive.documents_chunked

